### ISSUE TITLE
go get doesn't work for me

### ISSUE THREAD

**Issue by ketancmaheshwari** [benhoyt/goawk#1]
[ketan@localhost ~]$ go get github.com/benhoyt/goawk
[ketan@localhost ~]$ goawk 'BEGIN { print "foo", 42 }'
bash: goawk: command not found...
[ketan@localhost ~]$ which go
/usr/bin/go
[ketan@localhost ~]$ go version
go version go1.9.4 linux/amd64

**Comment by jftuga** [comment]
go get github.com/benhoyt/goawk

This works OK on Win 10 with go version 1.10.3

    C:\>goawk
    usage: goawk [-F fs] [-v var=value] [-f progfile | 'prog'] [file ...]

**Comment by benhoyt** [comment]
@ketancmaheshwari Yeah, I think this is simply because the Go binary directory (`$GOPATH/bin`) is not in your PATH. Can you confirm?

**Comment by ketancmaheshwari** [comment]
I install go using yum. It gets installed in /usr/bin.

**Comment by jftuga** [comment]
On Windows 10, this is what I have:

    GOPATH=C:\Users\jftuga\go
    GOROOT=C:\Go\
    Path=C:\Windows\system32;....;%GOPATH%\bin

**Comment by benhoyt** [comment]
I'm going to assume this is a GOPATH issue per above and close.
