### ISSUE TITLE
Trailing spaces after comma confuse -i csv feature.

### ISSUE THREAD

**Issue by ghshephard** [benhoyt/goawk#109]
Not sure if this is as expected or unexpected or (most likely) undefined:

If we have a trailing space after a "," such as:
```
$ cat simple_space.csv
field1,field2,field3
"AAA, BBB", CCC, "DDD, EEE"
F,G,H
```
The goawk seems to have trouble figuring out what is an actual field.

```
$ goawk -i csv 'NR>1{print "F1:"$1,"F2:"$2,"F3:"$3}' simple_space.csv
F1:AAA, BBB F2: CCC F3: "DDD
F1:F F2:G F3:H
```

If trailing spaces are undefined in a CSV file, then probably can be closed as "won't fix"

**Comment by ghshephard** [comment]
Yeah - I'm going to close this as "Undefined or otherwise corrupt CSV file" - awk with FPAT and python do the same thing:

```
import csv

with open("simple_space.csv") as f:
    csv_reader=csv.reader(f)
    for l in csv_reader:
        print(f'F1:{l[0]} F2:{l[1]} F3:{l[2]}')
```
        
Yields same behavior:

```
$ python pycsv.py 
F1:field1 F2:field2 F3:field3
F1:AAA, BBB F2: CCC F3: "DDD
F1:F F2:G F3:H
```

**Comment by benhoyt** [comment]
Yeah, this is as expected. Go's encoding/csv Reader has a `TrimLeadingSpace` option, but I don't currently turn that on or expose that in GoAWK. For example: https://go.dev/play/p/BkcRx_vzork

I'd definitely consider adding a `trimleadingspace` option to `INPUTMODE` if it proves valuable on real-world data. I'm curious though, did you create that CSV file by hand as a test, or did this problem occur in real-world CSV files you got from somewhere else?

**Comment by benhoyt** [comment]
Thanks for the report, though -- appreciated!

**Comment by ghshephard** [comment]
It was a test file - but, I have seen precisely that issue (and oh lord, so many more) when customers try and generate their own CSV files without using a library.   Usually the first time a field has a "," that they don't account for, everything comes crushing down - but sometimes they save data that has leading spaces, and neglect to trim it (or, perhaps better yet, enclose in quotation marks) - Super excited to make goawk a part of my finder-dna-data-engineering behavior.   You would be shocked at how much of my job/income awk has been for the last 15+ years....
