### ISSUE TITLE
difference between awk and goawk in csv mode

### ISSUE THREAD

**Issue by mickmcq** [benhoyt/goawk#118]
I have a csv file that, by necessity, includes some blank lines. If I print the file using awk, e.g.,

```bash
awk '{print}' filename
```

the blank lines are printed. If instead I print the file using goawk in csv mode, e.g.,

```bash
goawk -i csv -o csv '{print}' filename
```

the blank lines are skipped. Is there some way to include the blank lines while still using goawk in csv mode?

**Comment by benhoyt** [comment]
Hi Mike, for better or worse, this is by design, as you normally don't want blank lines included in the data: GoAWK's CSV reader skips blank lines (Go's `encoding/csv.Reader` does the same) because they're not part of the CSV data itself. So when you output the rows the blank lines are missing.

Can you give an example of your input, even just a few lines showing context? Or perhaps explain why the blank lines or needed here, and how we might be able to work around this?

**Comment by mickmcq** [comment]
Yes, I can give you the example, but it is somewhat frustrating. It is an
input file for the Weka machine learning system. The input file has a
header which includes blank lines, followed by csv data for the famous iris
dataset. It would be far better for Weka to use some kind of known standard
for its header, but this is what I have to work with. I accept that there
may be no solution beyond manually editing such files, but thought I'd give
it a try. The task here, as part of a chain of commands, is to alter some
of the csv data using Awk. I thought it would be a good place to try GoAwk
because the csv data to be altered is only in the third and fourth columns
of the versicolor section of the data.

- Mick

The file follows:

@RELATION iris_discretized

@ATTRIBUTE sepallength {low,medium,high}
@ATTRIBUTE sepalwidth {low,medium,high}
@ATTRIBUTE petallength {low,medium,high}
@ATTRIBUTE petalwidth {low,medium,high}
@ATTRIBUTE class {Iris-setosa,Iris-versicolor,Iris-virginica}

@DATA

low,medium,low,low,Iris-setosa
low,medium,low,low,Iris-setosa
low,medium,low,low,Iris-setosa
low,medium,low,low,Iris-setosa
low,high,low,low,Iris-setosa
low,high,low,low,Iris-setosa
low,medium,low,low,Iris-setosa
low,medium,low,low,Iris-setosa
low,medium,low,low,Iris-setosa
low,medium,low,low,Iris-setosa
low,high,low,low,Iris-setosa
low,medium,low,low,Iris-setosa
low,medium,low,low,Iris-setosa
low,medium,low,low,Iris-setosa
medium,high,low,low,Iris-setosa
medium,high,low,low,Iris-setosa
low,high,low,low,Iris-setosa
low,medium,low,low,Iris-setosa
medium,high,low,low,Iris-setosa
low,high,low,low,Iris-setosa
low,medium,low,low,Iris-setosa
low,high,low,low,Iris-setosa
low,high,low,low,Iris-setosa
low,medium,low,low,Iris-setosa
low,medium,low,low,Iris-setosa
low,medium,low,low,Iris-setosa
low,medium,low,low,Iris-setosa
low,medium,low,low,Iris-setosa
low,medium,low,low,Iris-setosa
low,medium,low,low,Iris-setosa
low,medium,low,low,Iris-setosa
low,medium,low,low,Iris-setosa
low,high,low,low,Iris-setosa
medium,high,low,low,Iris-setosa
low,medium,low,low,Iris-setosa
low,medium,low,low,Iris-setosa
medium,medium,low,low,Iris-setosa
low,medium,low,low,Iris-setosa
low,medium,low,low,Iris-setosa
low,medium,low,low,Iris-setosa
low,medium,low,low,Iris-setosa
low,low,low,low,Iris-setosa
low,medium,low,low,Iris-setosa
low,medium,low,low,Iris-setosa
low,high,low,low,Iris-setosa
low,medium,low,low,Iris-setosa
low,high,low,low,Iris-setosa
low,medium,low,low,Iris-setosa
low,high,low,low,Iris-setosa
low,medium,low,low,Iris-setosa
high,medium,medium,medium,Iris-versicolor
medium,medium,medium,medium,Iris-versicolor
high,medium,medium,medium,Iris-versicolor
medium,low,medium,medium,Iris-versicolor
medium,medium,medium,medium,Iris-versicolor
medium,medium,medium,medium,Iris-versicolor
medium,medium,medium,medium,Iris-versicolor
low,low,medium,medium,Iris-versicolor
medium,medium,medium,medium,Iris-versicolor
low,low,medium,medium,Iris-versicolor
low,low,medium,medium,Iris-versicolor
medium,medium,medium,medium,Iris-versicolor
medium,low,medium,medium,Iris-versicolor
medium,medium,medium,medium,Iris-versicolor
medium,medium,medium,medium,Iris-versicolor
high,medium,medium,medium,Iris-versicolor
medium,medium,medium,medium,Iris-versicolor
medium,low,medium,medium,Iris-versicolor
medium,low,medium,medium,Iris-versicolor
medium,low,medium,medium,Iris-versicolor
medium,medium,medium,high,Iris-versicolor
medium,medium,medium,medium,Iris-versicolor
medium,low,medium,medium,Iris-versicolor
medium,medium,medium,medium,Iris-versicolor
medium,medium,medium,medium,Iris-versicolor
medium,medium,medium,medium,Iris-versicolor
high,medium,medium,medium,Iris-versicolor
high,medium,high,high,Iris-versicolor
medium,medium,medium,medium,Iris-versicolor
medium,low,medium,medium,Iris-versicolor
medium,low,medium,medium,Iris-versicolor
medium,low,medium,medium,Iris-versicolor
medium,low,medium,medium,Iris-versicolor
medium,low,high,medium,Iris-versicolor
low,medium,medium,medium,Iris-versicolor
medium,medium,medium,medium,Iris-versicolor
high,medium,medium,medium,Iris-versicolor
medium,low,medium,medium,Iris-versicolor
medium,medium,medium,medium,Iris-versicolor
medium,low,medium,medium,Iris-versicolor
medium,low,medium,medium,Iris-versicolor
medium,medium,medium,medium,Iris-versicolor
medium,low,medium,medium,Iris-versicolor
low,low,medium,medium,Iris-versicolor
medium,low,medium,medium,Iris-versicolor
medium,medium,medium,medium,Iris-versicolor
medium,medium,medium,medium,Iris-versicolor
medium,medium,medium,medium,Iris-versicolor
low,low,medium,medium,Iris-versicolor
medium,medium,medium,medium,Iris-versicolor
medium,medium,high,high,Iris-virginica
medium,low,high,high,Iris-virginica
high,medium,high,high,Iris-virginica
medium,medium,high,high,Iris-virginica
medium,medium,high,high,Iris-virginica
high,medium,high,high,Iris-virginica
low,low,medium,high,Iris-virginica
high,medium,high,high,Iris-virginica
high,low,high,high,Iris-virginica
high,high,high,high,Iris-virginica
medium,medium,high,high,Iris-virginica
medium,low,high,high,Iris-virginica
high,medium,high,high,Iris-virginica
medium,low,high,high,Iris-virginica
medium,medium,high,high,Iris-virginica
medium,medium,high,high,Iris-virginica
medium,medium,high,high,Iris-virginica
high,high,high,high,Iris-virginica
high,low,high,high,Iris-virginica
medium,low,high,medium,Iris-virginica
high,medium,high,high,Iris-virginica
medium,medium,medium,high,Iris-virginica
high,medium,high,high,Iris-virginica
medium,low,medium,high,Iris-virginica
high,medium,high,high,Iris-virginica
high,medium,high,high,Iris-virginica
medium,medium,medium,high,Iris-virginica
medium,medium,medium,high,Iris-virginica
medium,medium,high,high,Iris-virginica
high,medium,high,medium,Iris-virginica
high,medium,high,high,Iris-virginica
high,high,high,high,Iris-virginica
medium,medium,high,high,Iris-virginica
medium,medium,high,medium,Iris-virginica
medium,low,high,medium,Iris-virginica
high,medium,high,high,Iris-virginica
medium,medium,high,high,Iris-virginica
medium,medium,high,high,Iris-virginica
medium,medium,medium,high,Iris-virginica
high,medium,high,high,Iris-virginica
high,medium,high,high,Iris-virginica
high,medium,high,high,Iris-virginica
medium,low,high,high,Iris-virginica
high,medium,high,high,Iris-virginica
high,medium,high,high,Iris-virginica
high,medium,high,high,Iris-virginica
medium,low,high,high,Iris-virginica
medium,medium,high,high,Iris-virginica
medium,medium,high,high,Iris-virginica
medium,medium,high,high,Iris-virginica

**Comment by mickmcq** [comment]
Actually, let me not waste more of your time on this issue. Knowing that it is by design and is in the underlying Go code is enough. I can just work around it by stripping the header and printing it in a separate script without disturbing the workflow.

**Comment by benhoyt** [comment]
Yeah, that makes sense to me. In this case I think the answer is "that data is not exactly CSV", particularly the `@...` lines. For this kind of custom format you might be better using goawk (or plain awk/gawk) in non-CSV mode, just looking for the `@Data` and then splitting on `FS=","` (there doesn't seem to be quoting in this data in any case).
