### ISSUE TITLE
Feature request for embedded use

### ISSUE THREAD

**Issue by rayjlinden** [benhoyt/goawk#14]
This is really cool.  Your article about how you wrote it is even better.  Congrats!

I have a scenario that would be cool to handle if possible.  Your readme shows how you can run the parser from go.  The print statements are just going to stdio I assume.  It would be cool if in embedded code like that I could route results to another go routine.

The idea is to read some large files of data.  Awk is great at the first processing of that data but then I want to be able to operate on that output at the same time (and in a steaming vs. batch way as the inout can be rather large.)

I'm just spit-balling - but it would be cool if in the embedded case you could register channels with the interpreter and then has a special chan function that could be used to send data to the named channel. 

In any case, good work.  I've always been a fan of AWK and I'm doing a lot of Go now - so this is really fun to see.

**Comment by benhoyt** [comment]
Hi @rayjlinden, thanks for the feedback -- I had a lot of fun writing it (both GoAWK and the article).

If I'm understanding you correctly, you can already do what you're suggesting by calling `interp.Exec(src, fieldSep, reader, writer)` with writer set to a custom `io.Writer`. This may be enough, or if you want to process the output as it's running you'd fire up a goroutine to "listen" to writes on the custom writer.

**Comment by benhoyt** [comment]
Closing as I believe you can do this already per above.
