### ISSUE TITLE
Should the output of `-d` option be 100% correct AWK code equivalent to the source?

### ISSUE THREAD

**Issue by xonixx** [benhoyt/goawk#142]
Looks like I found cases when this is not the case, or at least GoAWK refuses to parse back that code.

I'll provide more information regarding the case if need be.

**Comment by benhoyt** [comment]
Hi @xonixx -- no, `-d` isn't guaranteed to be 100% correct AWK code, just a human-readable dump of the parse tree for debugging. I know it doesn't add parenthesis in some places to get the operator precedence correct in some cases. However, I'd be interested to see what you found -- if it's an easy fix I'd be happy to do it.

**Comment by xonixx** [comment]
Thanks, no problem then.
