### ISSUE TITLE
Should coverage profiles use relative filenames?

### ISSUE THREAD

**Issue by benhoyt** [benhoyt/goawk#161]
Hi @xonixx, I'm wondering whether the coverage profile files should have relative filenames, rather than absolute? The advantage being that it won't then show the full path (including your home directory like `/home/ben`) in the HTML version. For example, the current output is:

```
$ goawk -coverprofile=cover.out -f prog.awk
will always run
should run
$ cat cover.out
mode: set
/home/ben/h/goawk/prog.awk:4.9,4.27 1 1
/home/ben/h/goawk/prog.awk:6.9,6.26 1 0
/home/ben/h/goawk/prog.awk:2.5,3.19 2 1
```

I'm proposing we change it to this:

```
mode: set
./prog.awk:4.9,4.27 1 1
./prog.awk:6.9,6.26 1 0
./prog.awk:2.5,3.19 2 1
```

I did this manually for the [updated screenshot in the docs](https://github.com/benhoyt/goawk/blob/ee33d15f3c9b345e8085cdde54b3c26f94c266da/docs/cover.png), so that it shortened the path and didn't show my home directory in there.

On the other hand, the advantage of absolute is that then you can move the coverage file around and `go tool cover` will still be able to find the source. (I don't imagine most people move those around, however -- I certainly never have.) The Go tool with `go test -coverprofile` outputs full import paths, not filesystem paths, like so:

```
$ go test -coverprofile=cover.out ./interp
ok  	github.com/benhoyt/goawk/interp	1.613s	coverage: 93.1% of statements
$ head -n4 cover.out
mode: set
github.com/benhoyt/goawk/interp/io.go:25.65,27.16 2 1
github.com/benhoyt/goawk/interp/io.go:30.2,30.47 1 1
github.com/benhoyt/goawk/interp/io.go:27.16,29.3 1 0
```

**Comment by xonixx** [comment]
We can do this, but in accordance with principle [worse is better](https://en.wikipedia.org/wiki/Worse_is_better) I would probably prefer to keep it absolute. 
For example in my use case [I generate the coverage report in `/tmp`](https://github.com/xonixx/makesure/blob/main/Makesurefile#L121). So I think in this case the relative path will be even uglier, lile `../home/xonix/proj/makesure/makesure.awk`.

**Comment by benhoyt** [comment]
No problems, I'll leave it as is for now.
