### ISSUE TITLE
Deleting from array while looping

### ISSUE THREAD

**Issue by n8ta** [benhoyt/goawk#163]
This program has different output compared to mawk/gnu-awk (not just due to order of keys in the loop).

```awk
BEGIN {
  arr[0] = "zero"; 
  arr[1] = "one"; 
  for (k in arr) { 
      print "key " k " val " arr[k]; 
      delete arr[k+1]  
  }
}
```

Goawk produces this (only executing the loop once)
``` 
key 0 val zero
```

gnu-awk produces this (executing the loop twice but with arr[k] being the empty string after being deleted)
```
key 0 val zero
key 1 val
```

Mawk sorts keys differently so you need to tweak the program to be k-1 to see the behavior (at least on my machine).
``` 
mawk   'BEGIN { arr[0] = "zero"; arr[1] = "one"; for (k in arr) { print "key " k " val " arr[k]; delete arr[k-1]  } }'
key 1 val one
key 0 val
```

Goawk's behavior seems reasonable to me but gnu-awk and mawk both behave differently (even with -P for gawk). Any idea what the correct thing to do here is? The spec does say "The results of adding new elements to _array_ within such a for loop are undefined.", but that's not helpful for deletions

**Comment by benhoyt** [comment]
Interesting! Yeah, the spec doesn't seem to define this, though I think a reasonable assumption (extrapolating the bit you quoted about adding new elements) would be that it's not specified and the implementation is free to yield the deleted element (gawk, mawk), or not yield it (GoAWK, original-awk).

Note that apart from the question of how `delete` interactions with iteration, there's also the question of iteration order itself. The POSIX AWK spec says that the implementation can iterate "in an unspecified order". GoAWK does just that, and actually uses Go's map iteration order, which varies from iteration to iteration. In this case for whatever reason Go *usually* iterates 0 first, then 1 ... but if you run it a dozen times or so, you'll see it iterate the other way:

```
# case where 0 is iterated first (seems to be more common)
$ goawk -f t.awk
key 0 val zero
# every so often 1 is iterated first
$ goawk -f t.awk
key 1 val one
key 0 val zero
```

GoAWK also uses Go's `delete()` semantics, which is that "If a map entry that has not yet been reached is removed during iteration, the corresponding iteration value will not be produced." In other words, if the 0 is iterated first, the 1 will be deleted and not shown at all; but if the 1 is iterated first, GoAWK will try to delete 2, which doesn't exist so it'll do nothing, and then show the 0 after.

Note also that original-awk ("one true awk") seems to iterate the 0 first, and delete the 1:

```
$ original-awk -f t.awk
key 0 val zero
```

In any case, given the above, I think GoAWK's behaviour is within spec here.

**Comment by n8ta** [comment]
Yes I did notice goawk is the only one to iterate in an (obviously) varying order but that's completely fair given the spec and seems natural for a go impl. If onetrueawk agrees with you I'm a lot more confident that this a fair interpretation of the spec (:

I really don't like the gawk/mawk behavior of yielding a deleted key; happy you did not got go that way.
