### ISSUE TITLE
Go AWK seems to have problems with constructs other interpreters don't

### ISSUE THREAD

**Issue by ericpruitt** [benhoyt/goawk#2]
I have a pure-AWK implementation of _wcwdith(3)_ that I've written that can be found at <https://github.com/ericpruitt/wcwidth.awk>. The test suite for that script runs against BusyBox AWK, GNU Awk, MAWK and "One True AWK" without issue, but it doesn't work with your Go AWK. There appear to be at least two issues. One is parsing; Go AWK doesn't like the placement of one of my break statements:

~~~
buildbox@sinister:wcwidth.awk [1]$ goawk -f wcwidth.awk
-------------------------------------------------------
            break
            ^
-------------------------------------------------------
parse error at 165:13: break must be inside a loop body
(1)
buildbox@sinister:wcwidth.awk [1]$ cat -n wcwidth.awk | grep -C2 165
   163          } else if (WCWIDTH_POSIX_MODE) {
   164              _total = -1
   165              break
   166          } else {
   167              # Ignore non-printable ASCII characters.
~~~

The other issue has to do with the way command line arguments are handled. AWK lets you modify the ARGV array, so not all arguments need to be options or file paths. Go AWK tries to treat an argument as a file path when it shouldn't:

~~~
buildbox@sinister:wcwidth.awk [1]$ goawk -f wcwidth.awk -f test.awk -v TERSE=1 width-data:width-data
open width-data:width-data: no such file or directory
(1)
~~~

Original AWK (and the other interpreters) have no problem with this:
~~~
buildbox@sinister:wcwidth.awk [1]$ original-awk -f wcwidth.awk -f test.awk -v TERSE=1 width-data:width-data
buildbox@sinister:wcwidth.awk [1]$
~~~

**Comment by benhoyt** [comment]
Interesting, thanks for the report!

GoAWK does have a couple of known parsing issues (but I haven't seen real code run into them yet). However, I can't repro the error your seeing, as it seems the copy of wcwidth.awk that you're running against is different from what's on GitHub now (the lines don't match up to what you've showed). When I run the wcwidth.awk on GitHub, I get:

    $ ./goawk -f wcwidth.awk foo
    wcwidth: the AWK interpreter is not multi-byte safe and its sprintf implementation does not support manual composition of UTF-8 sequences.

As for the other issue, I didn't actually know you could specify multiple `-f` source files, so I'll need to fix that. With the ARGV thing, I'm not actually sure what's going on there -- I'll look into it.

**Comment by ericpruitt** [comment]
> as it seems the copy of wcwidth.awk that you're running against is different from what's on GitHub now

Right you are. I pushed the two commits that were missing from the GitHub hosted repository.

> wcwidth: the AWK interpreter is not multi-byte safe and its sprintf implementation does not support manual composition of UTF-8 sequences.

My script relies on AWK's sprintf emitting bytes to build UTF-8 sequences, so unless you decide to support that, 

> As for the other issue, I didn't actually know you could specify multiple -f source files, so I'll need to fix that. With the ARGV thing, I'm not actually sure what's going on there -- I'll look into it.

Have you looked at the POSIX specification for AWK? If not, I'd suggest you do; you can find it at <http://pubs.opengroup.org/onlinepubs/9699919799/utilities/awk.html>. In my opinion, it does a very good job of explaining how AWK interpreters should work, and I haven't noticed many significant differences from what it prescribes versus real-world implementations.

> `sprintf implementation does not support manual composition of UTF-8 sequences.`

Assuming my error message / detection heuristic is correct, I'd also recommend revising how your "sprintf" function works since it's essential for non-ASCII output or making your AWK support UTF-8 sequences. If it matters, GNU Awk is the only interpreter I'm aware of that supports multi-byte sequences.

**Comment by benhoyt** [comment]
I've pushed a fix for the first part of this issue (handling of `break`) in https://github.com/benhoyt/goawk/commit/65c6b2c23c862e221e3753ea2ba89b0ba3e993a0. I'll look at the command-line handling later.

**Comment by benhoyt** [comment]
I just pushed a fix for the ARGV handling issue in https://github.com/benhoyt/goawk/commit/e7a6e44e2fc0365ceaf65cf3c24642fbb216be22. Thanks for the report(s). As for the UTF-8 / multi-byte handling, I'm going to look at that at some point soon.

> Have you looked at the POSIX specification for AWK?

Yeah, definitely. I looked at this reasonably closely when implementing GoAWK, and it helped a ton implementing parsing and interpreting. However, I kinda skimmed on the command line handling parts of it...

**Comment by benhoyt** [comment]
@ericpruitt What would you recommend with regard to sprintf handling of UTF-8? Currently you can just pass UTF-8 directly through and it "supports" it by leaving it untouched, for example:

    $ ./goawk 'BEGIN { printf "“Smart quotes,”\n" }'
    “Smart quotes,”

**Comment by ericpruitt** [comment]
It looks like my method of detecting "sprintf" and "printf" implementations that do (or do not) work with Unicode doesn't work with GoAWK for some reason. I was expecting `goawk 'BEGIN { printf "%c\n", 23485 }'` to not work based on the error message from wcwidth.awk, but GoAWK prints "宽" as it should. I'll look into this tomorrow to figure out what's actually going on here and follow-up with you.

**Comment by ericpruitt** [comment]
It seems you've got a weird mix of treating the data as bytes and runes. The reason my wcwidth scripts fails is that GoAWK supports wide characters, but your "length" function returns the number of bytes:
```
$ goawk 'BEGIN { print sprintf("%c", 23485), length(sprintf("%c", 23485)) }'
宽 3
```

Similarly, your "substr" function surprisingly (IMO) operates on bytes instead of runes:

```
$ goawk 'BEGIN { print substr(sprintf("%c", 23485), 1,1) }' | xxd
00000000: e50a
```

Since "%c" represents a single character and your "sprintf" gladly accepts Unicode code-points, I would expect all of your string-related functions to work with runes. I think you should either make everything treat strings as rune arrays (GNU Awk) or make everything treat strings as byte arrays (everything else).

**Comment by benhoyt** [comment]
Huh, interesting. This behaviour reflects Go's string slice (`s[start:stop]`) and `len(s)` operations, but I can see how it's confusing. I'll think about this further. Looks like the POSIX spec talks about "characters" and not bytes.
