### ISSUE TITLE
Allow length(array) in addition to length(string)

### ISSUE THREAD

**Issue by knieriem** [benhoyt/goawk#20]
Apparently length() can't be called with an array argument currently. If I'm not mistaken, that's POSIX behaviour. Though, various other `awk`s support it. The following program:

	BEGIN {
		split("abc", a, "")
		for (i=1; i<=length(a); i++) {
			print a[i]
		}
		exit
	}

, run with `goawk`, will print `parse error: can't use array "a" as scalar`. As I noticed, I can work around it using `n = split(...`. So perhaps in this case it is not much of a problem, but I opened the issue nonetheless, just in case this isn't intended.

**Comment by benhoyt** [comment]
Thanks @knieriem. This is (more or less) intended, as I'm following POSIX here. I also think it's a bit weird (in AWK terms) that a function can take both a scalar and an array. As you say, it's easy to work around, so I think I'll leave it.

**Comment by benhoyt** [comment]
I've decided to reopen this as -- despite not being mentioned in the POSIX spec -- this is supported by all awk versions except GoAWK (onetrueawk, Gawk, mawk, busybox awk, frawk). And it's quite useful.

**Comment by benhoyt** [comment]
It's apparently been accepted for inclusion into POSIX (https://www.austingroupbugs.net/view.php?id=1566) but not yet added to the spec

**Comment by benhoyt** [comment]
Finally fixed this, more than four years after the issue was opened. Thanks @knieriem. :-)
