### ISSUE TITLE
fflush() stops on first flush error

### ISSUE THREAD

**Issue by juster** [benhoyt/goawk#208]
During my reading of the `interp.flushAll` method I noticed that it accidentally uses conditional evaluation. Because the `&&` operator is "short-circuited", if any `Flush()` returns a non-nil error, then all of the following `Flush()`-es will be skipped. `allGood` will be false so the right-hand side of `&&` will not be evaluated.

```go
// Flush all output streams as well as standard output. Report whether all
// streams were flushed successfully (logging error(s) if not).
func (p *interp) flushAll() bool {
	allGood := true
	for name, writer := range p.outputStreams {
		allGood = allGood && p.flushWriter(name, writer)
	}
	if _, ok := p.output.(flusher); ok {
		// User-provided output may or may not be flushable
		allGood = allGood && p.flushWriter("stdout", p.output)
	}
	return allGood
}
```

Code changes are trivial but I'm not sure how to create a regression test as an interpreter "black box" test.

**Comment by juster** [comment]
Let me know if you want me to add regression tests.

**Comment by benhoyt** [comment]
Thanks for the bug report and fix! Out of interest, did you notice this when looking at the code, or did you run into it happening?

**Comment by juster** [comment]
This was purely from reading the code.
