### ISSUE TITLE
Allow line break between `}` and `while`

### ISSUE THREAD

**Issue by oguz-ismail** [benhoyt/goawk#219]
See:
```
$ goawk 'BEGIN{do{}
while(0)}'
<cmdline>:1:11: expected while instead of <newline>
BEGIN{do{}
          ^
$
```
POSIX allows line breaks after every closing brace, the one terminating a `do` group is no exception.

**Comment by benhoyt** [comment]
Fixed and merged in #220. Thanks for the report!
