### ISSUE TITLE
goawk should allow argument to -F to be up against the -F

### ISSUE THREAD

**Issue by arnoldrobbins** [benhoyt/goawk#22]
Compare all other awks:

``$ gawk -F: '/arnold/ { print $5 }' /etc/passwd``
``Arnold Robbins,,,``

to goawk:

``$ goawk -F: '/arnold/ { print $5 }' /etc/passwd``
``flag provided but not defined: -F:``

Goawk requires that the option and argument be separate:

``$ goawk -F : '/arnold/ { print $5 }' /etc/passwd``
``Arnold Robbins,,,``

This is also contrary to POSIX.

Thanks.

**Comment by benhoyt** [comment]
Will release this fix in v1.5.1 in a few days.

**Comment by arnoldrobbins** [comment]
Great! Much thanks.
