### ISSUE TITLE
{} behaves like 1, END{} doesn't exhaust input

### ISSUE THREAD

**Issue by oguz-ismail** [benhoyt/goawk#228]
See:
```
$ seq 3 | goawk '{}'
1
2
3
$ seq 3 | { goawk 'END{}'; wc -l;}
3
```
According to POSIX the first command shouldn't print anything, and the second should print 0.

**Comment by benhoyt** [comment]
Ah, that's an interesting bug -- I'm surprised I hadn't noticed it before. Thanks for the report! I'll take a look in the next couple of weeks.

**Comment by benhoyt** [comment]
Fixed -- thanks for the report.
