### ISSUE TITLE
Support for %i in format strings.

### ISSUE THREAD

**Issue by JohnEarnest** [benhoyt/goawk#229]
The [POSIX spec](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap05.html#tag_05) permits using `%i` as an alternative to `%d`. This is supported by most awk implementations:
```
% awk 'BEGIN{printf("%i\n",42)}' 
42
% mawk 'BEGIN{printf("%i\n",42)}'
42
% gawk 'BEGIN{printf("%i\n",42)}'
42
```

GoAWK v1.27.0 does not interpret `%i` correctly:
```
% goawk 'BEGIN{printf("%i\n",42)}'
%!i(int=42)
```

**Comment by benhoyt** [comment]
Thanks for the report. Are you interested in fixing this? I suspect it'll be fairly trivial.

It looks like `%a` and `%A` don't work either (at a quick glance, looks like they should be equivalent to `%x` / `%X`). Not sure if that will be trivial or not.

**Comment by JohnEarnest** [comment]
I don't program in Go; I'd rather not work up a PR. Just reporting an inconsistency I tripped over while testing the portability of my Awk scripts.

**Comment by benhoyt** [comment]
@JohnEarnest That's fine, I'll get to it at some point. Thanks again for the report.

**Comment by benhoyt** [comment]
Thanks again for the report. The fix is merged into `master` now. That fix also adds support for `%a` and `%A` and fixes the behaviour of %o, %x, %X (they should have been unsigned).
