### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by cup** [benhoyt/goawk#23]
I see no binary releases here

https://github.com/benhoyt/goawk/releases

**Comment by benhoyt** [comment]
No, sorry @cup -- I don't have ready access to Windows or Linux machines to produce binaries. Oh wait -- I guess I could cross-compile and upload those easily? Then again, it's super-easy to create Go binaries (`go build` or `go install`) so I don't consider this a real problem.

**Comment by cup** [comment]
@benhoyt you are correct - the process is trivial if you have a Go environment
installed.

However some users perhaps cant or wont do that, and it might help adoption of
this project if that barrier was removed. consider that many large Go projects
are doing this already:

- https://github.com/gohugoio/hugo/releases
- https://github.com/gogs/gogs/releases
- https://github.com/syncthing/syncthing/releases
- https://github.com/etcd-io/etcd/releases
- https://github.com/fatedier/frp/releases

**Comment by benhoyt** [comment]
I have got the script to create these binaries. However, reopening the issue until I get back to a decent internet connection where I can actually upload them.

**Comment by benhoyt** [comment]
Done, see https://github.com/benhoyt/goawk/releases/tag/v1.5.1 -- I've tested the macOS 64-bit one. Can you please test the download relevant to your system?

**Comment by cup** [comment]
Using this test:

~~~sh
goawk 'BEGIN { print "hello world" }'
~~~

Passes with these:

- goawk_v1.5.1_windows_amd64.zip
- goawk_v1.5.1_windows_386.zip
- goawk_v1.5.1_linux_amd64.tar.gz
- goawk_v1.5.1_linux_386.tar.gz

**Comment by benhoyt** [comment]
Awesome, thanks for suggesting this, closing.
