### ISSUE TITLE
FIELDWIDTHS no effective

### ISSUE THREAD

**Issue by happydentist** [benhoyt/goawk#244]
gawk $1=$1" OFS=, FIELDWIDTHS="10 2 6 1" can split fixedwidth text file to csv format
But goawk cannot，it just recognize space character for field seprator

**Comment by benhoyt** [comment]
Sorry, `FIELDWIDTHS` is a Gawk-specific feature that I have no plans to implement in GoAWK. For POSIX AWK, you can use `substr` manually to split such fields.
