### ISSUE TITLE
Release FreeBSD binary.

### ISSUE THREAD

**Issue by derekmahar** [benhoyt/goawk#246]
Please build and release a FreeBSD binary in addition to the Darwin, Linux, and Windows binaries.

**Comment by benhoyt** [comment]
Which architecture are important? [Possible values](https://go.dev/doc/install/source#environment) are:

	freebsd 	386
	freebsd 	amd64
	freebsd 	arm
 
Out of interest, what do you use GoAWK for?

**Comment by derekmahar** [comment]
I'm interested in amd64, but others may run FreeBSD on ARM processors in single board computers like the Raspberry Pi.

I use GoAWK for processing CSV files along with tools like csvtk, csvq, DuckDB, Miller, qsv, and Python modules or packages like csv, Pandas, and Polars.

Do you know if GoAWK is available in FreeBSD ports?  I run TrueNAS, a FreeBSD derivative, which does not include any compilers in its base "immutable" operating system, so if GoAWK were available in Ports, its build would have to first build the Go compiler and any other dependencies.

**Comment by benhoyt** [comment]
Thanks for the info. Unfortunately I know very little about FreeBSD, but a [quick search here](https://ports.freebsd.org/cgi/ports.cgi?query=goawk&stype=all&sektion=all) shows that v1.29.0 is in Ports (if I'm looking at the right place).

I've released [v1.29.1](https://github.com/benhoyt/goawk/releases/tag/v1.29.1) with FreeBSD amd64 and arm binaries, so closing this issue as complete.
