### ISSUE TITLE
Array creation

### ISSUE THREAD

**Issue by cup** [benhoyt/goawk#28]
AWK should have a variadic function for array creation. Currently if you wish to
create an array, you must use this:

~~~awk
dd[1] = "aa"
dd[2] = "bb"
dd[3] = "cc"
~~~

Or:

~~~awk
split("aa bb cc", dd)
~~~

the split syntax is problematic if your elements contain spaces. That can be
worked around by using a custom separator:

~~~awk
split("aa bb\1cc", dd, "\1")
~~~

but then it will fail again if your separator happens to be part of one of the
elements. Many other languages have syntax for array literals, for example C:

~~~c
char *dd[] = {"aa", "bb", "cc"};
~~~

Python:

~~~py
dd = ['aa', 'bb', 'cc']
~~~

JavaScript:

~~~js
var dd = ['aa', 'bb', 'cc'];
~~~

Ruby:

~~~rb
dd = ['aa', 'bb', 'cc']
~~~

Go:

~~~go
dd := []string {"aa", "bb", "cc"}
~~~

with AWK, it could look like one of these:

~~~awk
anew(dd, "aa", "bb", "cc")
dd[2] == "bb"
~~~

~~~awk
aset(dd, "aa", "bb", "cc")
dd[2] == "bb"
~~~

**Comment by benhoyt** [comment]
Hi Steven, I'd rather not add GoAWK-specific language extensions -- I'm not really interested in evolving the language beyond POSIX AWK. Sorry about that!

**Comment by cup** [comment]
@benhoyt I see youve said that now a couple of times:

- https://github.com/benhoyt/goawk/issues/28#issuecomment-495928969
- https://github.com/benhoyt/goawk/pull/15#issuecomment-441640328

but is that actually true?:

- https://github.com/benhoyt/goawk/issues/24
- https://github.com/benhoyt/goawk#basic-usage

it seems you are willing to add extensions that *you* like. Perhaps you could
modify your canned statement going forward?

**Comment by benhoyt** [comment]
Heh, you may be right - BDFL's privilege. :-) However, you'll note on the hex escape thing that "one true awk" works that way, so there's a precedent and no real reason to change it. I'm open to pulling non-POSIX things in if they're in awk or gawk, but I'll take them on a case-by-case basis.

Under "differences from AWK", the only language feature difference is the single quote thing -- I don't really consider this a new feature, just a helpful tokenization thing for Windows command lines (I used Windows for a long time so have a fair bit of empathy for Windows users).

What I might consider is extending the Go function call support to allow setting array values, and then someone could add their own `aset()` function. Though that might be tricky to get right...
