### ISSUE TITLE
Incorrect field splitting in presence of leading whitespace

### ISSUE THREAD

**Issue by masiulaniec** [benhoyt/goawk#30]
```
$ echo ' a b c' | awk '{print $1}'
a
$ 
```

I cannot see a way of reproducing the above program in goawk, see https://play.golang.org/p/IScP3wBt2Nz for a naive attempt that fails.

**Comment by benhoyt** [comment]
This is actually working as intended, and these two programs are not equivalent. The default field separator is a single space, which collapses all whitespace, including leading whitespace. GoAWK works the same way here:

```
$ echo ' a b c' | ./goawk '{print $1}'
a
```

The equivalent program is this: https://play.golang.org/p/AWFkbDekwxt

Also, you can see what happens in awk with the split regex you've given:

```
$ echo ' a b c' | awk -F'[ \t\n]+' '{print $1}'

```

Basically it *splits* on space, tab, or newline, but doesn't collapse leading and trailing whitespace as the special handle of a single space does.
