### ISSUE TITLE
Use of map[string]... to store arrays makes array access non-deterministic

### ISSUE THREAD

**Issue by deuill** [benhoyt/goawk#31]
I've been running into some issues trying to get consistent output from `goawk` with a fairly non-trivial [script I have](https://github.com/deuill/grawkit). It seems that arrays are stored as `map[string]value` types [internally](https://github.com/benhoyt/goawk/blob/1a4e25c71b2d8792192ecd827bb7464308a9da33/interp/interp.go#L86), which makes array access with `for (x in y)` non-deterministic.

Consider the following example:

```awk
BEGIN {
	str = "1,2,3,4"
	split(str, fields, ",")
	for (i in fields) {printf "%d ", i}
}
```

For other AWK implementations I have access to (`nawk`, `gawk`, and `busybox awk`), this will return `1 2 3 4` (actually, that's a lie, `nawk` will return `2 3 4 1`, i.e. will return the first element last, for whatever reason). For `goawk`, as a consequence of randomized maps in Go, this will be random.

I don't assume people are writing non-trivial programs in Awk all the time, but having `for (x in y)` be non-deterministic is a pitfall, and is not always possible to work around (e.g. when keys are not known).

Is it possible that this will be fixed in the future?

**Comment by deuill** [comment]
That said, I dug a bit into the POSIX spec and it *does* state that `for ... in` iterates [in an unspecified order](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/awk.html#tag_20_06_13_09) so not sure what the resolution is here. Feel free to close if this isn't worth fixing.

**Comment by benhoyt** [comment]
Thanks for the report -- however, the POSIX spec says that the `for ... in` order is unspecified, and some implements don't iterate in order as you've noted, so I'm going to leave it as is. I could sort by alpha, but that would be a performance penalty, so given what the spec says I decided not to. The idiomatic way of iterating a (numeric) map in order would be something like this:

```awk
BEGIN {
  str = "a,b,c,d"
  n = split(str, fields, ",")
  for (i=1; i<=n; i++) {
    printf("%d: %s\n", i, fields[i])
  }
}
```

Or you could avoid the `n` assignment and do it like this (but I prefer the first version):

```awk
BEGIN {
  str = "a,b,c,d"
  split(str, fields, ",")
  for (i=1; i in fields; i++) {
    printf("%d: %s\n", i, fields[i])
  }
}
```

**Comment by deuill** [comment]
Thanks for the response -- indeed I managed to overcome the ordering by doing so, but I wonder what could be done for multi-dimensional arrays (not that there **is** such a thing in AWK) or arrays with string keys. I guess the spec doesn't cater for these, and probably never will.

Thanks for building and maintaining such a wonderful project!
