### ISSUE TITLE
Can this replace sed ?

### ISSUE THREAD

**Issue by winwisely99** [benhoyt/goawk#34]
If anyone has a decent answer it would be interesting.

Currently using sed for various hscky scripts and we are converting them into go and mage.

Hoawk could replace sed in this regards perhaps

**Comment by benhoyt** [comment]
Yeah, I think it probably could, but I don't know the kind of things you're doing with sed. Can you give some examples of the kinds of things you do with sed?

**Comment by benhoyt** [comment]
I'm happy to try to help if you post specific examples, but in the meantime, closing this issue (it's not really an issue with GoAWK).
