### ISSUE TITLE
Not interpreting NR multi-line awk syntax

### ISSUE THREAD

**Issue by fnzv** [benhoyt/goawk#39]
Hello there!
I was wondering if NR is working fine on this AWK library/interpreter, i was testing some examples and seems that NR when making diffs between different lines doesn't work while other simple commands works fine.

Example:
`awk ' NR == 1{old = $1; next} { print $1 - old; old = $1} '` (Taking the value from previous line and subtracting it to the current line)

Bash:
`cat numbers  | awk ' NR == 1{old = $1; next} { print $1 - old; old = $1} '`
`
3
-6
1
1
4
-7`

Goawk:
`$ go run awktest.go`
`4
7
1
2
3
7`

Bests,
Sami

**Comment by benhoyt** [comment]
Hi @fnzv, thanks for the report. I can't seem to reproduce this, however. I'm not quite sure what your `numbers` file looks like, but here's an attempt to repro this with `numbers` having the following contents:

```
4
7
1
2
3
7
0
```

Then when I type your example shell command, I get:

```
$ awk --version
GNU Awk 5.0.1, API: 2.0 (GNU MPFR 4.0.2, GNU MP 6.2.0)
...
$ cat numbers | awk ' NR == 1{old = $1; next} { print $1 - old; old = $1} '
3
-6
1
1
4
-7
```

But I get exactly the same thing when using GoAWK:

```
$ goawk --version
v1.6.1
$ cat numbers | goawk ' NR == 1{old = $1; next} { print $1 - old; old = $1} '
3
-6
1
1
4
-7
```

If you're still seeing this, can you please provide exact input and repro steps? (And your `goawk --version`.)

**Comment by fnzv** [comment]
Hi there!
i think it's somehow my fault but i don't know 
```
$ go run awktry.go
[52 10 55 10 49 10 50 10 51 10 55 10]
4
7
1
2
3
7

0
0
0
0
0
```

code:
```
package main

import (
	"bytes"
	"fmt"
	"io/ioutil"

	"github.com/benhoyt/goawk/interp"
)

func main() {
b, err := ioutil.ReadFile("numbers") // just pass the file name
if err != nil {
	fmt.Print(err)
}

fmt.Println(b) // print the content as 'bytes'

str := string(b) // convert content to a 'string'

fmt.Println(str) // print the content as a 'string'
		input := bytes.NewReader(b) 
		err = interp.Exec(`NR == 1{old = $10; next} { print $10 - old; old = $10} `, ",", input, nil)
		if err != nil {
			fmt.Println(err)
			return
		}
}
```
```
$ cat numbers | go run goawk.go  ' NR == 1{old = $1; next} { print $1 - old; old = $1} '
3
-6
1
1
4
$ go run goawk.go --version
v1.6.1
```

**Comment by benhoyt** [comment]
It looks like in your `awktry.go` code you're using `$10` instead of `$1` -- that would be the tenth field, which doesn't exist, so comes through as zero in the output. I can repro this locally, but if I change `$10` to `$1` it outputs the expected output (the 3 -6 1 1 4 sequence of lines).
