### ISSUE TITLE
How I can set output of interp.ExecProgram to a variable

### ISSUE THREAD

**Issue by Kingsley-C666** [benhoyt/goawk#40]
input:= `1T;2T;3T;4T;5T;6`
	src := "{ print $2,$3,$6 }"
	fieldSep := "T;"
	prog, err := parser.ParseProgram([]byte(src), nil)
	if err != nil {
		fmt.Println(err)
		return
	}
	config := &interp.Config{
		Stdin: bytes.NewReader([]byte(input)),
		Vars:  []string{"FS", fieldSep},
	}
	_, err = interp.ExecProgram(prog, config)
	if err != nil {
		fmt.Println(err)
		return
	}

**Comment by benhoyt** [comment]
Looks like you might have figured it out, but if not, you'd set the `Config.Output` field to a buffer of some sort, like this: https://play.golang.org/p/p--h0P3tDok

**Comment by Kingsley-C666** [comment]
Thank you
