### ISSUE TITLE
Support double hyphen (--) in argument parsing

### ISSUE THREAD

**Issue by essays-on-esotericism** [benhoyt/goawk#53]
Hello,

I've been experimenting with Goawk recently and I discovered that goawk does not accept double hyphens to indicate the end of options parsing.

Here's an example of what I'm talking about:

	$ awk -- '{print $1}' -file

The above snippet uses double hyphens to indicate the end of options parsing etc, and to allow for safely handling weird file names or untrusted input.

For example, if we have a file that we'd like to munge that is annoyingly named "-file"  and we do not use double hyphens, then the above snippet will fail because it parses "-file" as "-f ile", ie attempts to read a progfile from the non-existent file "ile".

Goawk however simply throws an an error: "flag provided but not defined: --".

Just thought I'd share my observations here.

Regards,

Jordan

**Comment by benhoyt** [comment]
Good call. It actually looks like both Gawk and (Brian Kernighan's) AWK don't even require the `--` for this case. This works fine:

```
$ awk '{print $1}' -file
```

because they stop parsing options at the first argument that doesn't start with a `-`. (Both Gawk and AWK also support an explicit `--`.)

I'd be happy to add these behaviours to GoAWK (but may not get to it for a while). If you do want to work up a PR, feel free!

**Comment by benhoyt** [comment]
@essays-on-esotericism Out of interest, what are you using GoAWK for?

**Comment by essays-on-esotericism** [comment]
Hey, sorry for the late reply, I was AFK for a couple of weeks there.

I took a look at bringing GoAWKS's double hyphens and end of options parsing  in line with that of the other awks, but my Go chops aren't good enough unfortunately.

In terms of what I'm using GoAWK for:
I'm using it to do a bunch of data munging in my pf-badhost and unbound-adblock projects.

For example, we use awk to parse internet registrar datasets from ARIN/APNIC etc to extract IP addresses, CIDR blocks and ASNs. This involves computing logarithms ,  performing character case conversions, string manipulations etc - all things in awks wheelhouse.

I do all sorts of data munging and input sanitization with awk in those projects, I'll include some links to it below if you're interested. I've added support for GoAWK in the latest 0.6 beta snapshot, as you'll see on the  project pages linked below.

# pf-badhost:
https://geoghegan.ca/pfbadhost.html
https://geoghegan.ca/pub/pf-badhost/beta/pf-badhost.sh

# unbound-adblock:
https://geoghegan.ca/unbound-adblock.html
https://geoghegan.ca/pub/unbound-adblock/beta/unbound-adblock.sh

**Comment by benhoyt** [comment]
This is fixed now on the master branch.

**Comment by essays-on-esotericism** [comment]
Excellent work, thanks for making GoAWK!
