### ISSUE TITLE
Incorrect `sh` determination for `system()`?

### ISSUE THREAD

**Issue by xonixx** [benhoyt/goawk#59]
Or at least inconsistent with major implementations:

```
$ PATH= ./soft/gawk51 'BEGIN { system("echo hello") }'
hello
$ PATH= ./soft/bwk 'BEGIN { system("echo hello") }'
hello
$ PATH= ./soft/mawk134 'BEGIN { system("echo hello") }'
hello
$ PATH= ./soft/goawk1.8.1 'BEGIN { system("echo hello") }'
exec: "sh": executable file not found in $PATH
$ ./soft/goawk1.8.1 'BEGIN { system("echo hello") }'
hello
```

AFAIK the `system()` call should use hardcoded `/bin/sh`

**Comment by benhoyt** [comment]
Yep, that looks like right. I've just looked at the Gawk source code and it hardcodes `/bin/sh` and uses `execl()` directly. AWK (bwk) calls `system()` which is documented to use `execl("/bin/sh", "sh", "-c", command, (char *) NULL);` under the hood.

I'd be happy for this to be fixed. Though I think it'd be good to add a field to the `interp.Config` struct called `Shell`, and if it's not set default to `/bin/sh` (on Unix; not sure what a good default is on Windows these days -- cmd.exe, Powershell?).

Are you interested in submitting a PR?

**Comment by xonixx** [comment]
Yes I think I would be able to add a PR.

I propose not to mix the two unrelated issues, though:

1. `/bin/sh` vs `sh` POSIX inconsistency.
2. Handling shell invocation on Windows.

I would be glad to provide a fix for item 1 above. 
To me item 2 requires much deeper consideration, testing, etc. 

@benhoyt Is this OK?

**Comment by benhoyt** [comment]
Yes, that's fine, thanks!

**Comment by benhoyt** [comment]
Squashed and merged your PR in https://github.com/benhoyt/goawk/commit/3e37e2071694d92e0c6ea7e0384339e1c72a4260 -- thanks!
