### ISSUE TITLE
new line under Windows

### ISSUE THREAD

**Issue by jftuga** [benhoyt/goawk#6]
Under Windows 10, goawk only output 0x0a for a newline. Windows splits the carriage return and new line characters. Under Windows, goawk should output 0x0d 0x0a

In other words, it need to output \r\n under Windows instead of just \n

Reference:

https://en.wikipedia.org/wiki/Newline#Representation

https://stackoverflow.com/questions/14493867/what-is-the-most-portable-cross-platform-way-to-represent-a-newline-in-go-golang

**Comment by jftuga** [comment]
It looks like the problem may stem from interp.go:137

    p.outputRecordSep = "\n"

Is there a way to make this cross-platform?

**Comment by benhoyt** [comment]
Thanks. Fixed in https://github.com/benhoyt/goawk/commit/b13da806d9e3b9d5770e0ebb0f10cfb33af97f6c

**Comment by jftuga** [comment]
This is working well.

The only issue I see is:

    works correctly:
    dir c:\windows\system32 /s/a-d/-c | .\goawk "{sum+=$4} END {print sum}"

    still only outputs 0x0a and not 0x0d 0x0a:
    dir c:\windows\system32 /s/a-d/-c | .\goawk "{sum+=$4} END {printf('%s\n', sum)}"

I realize that I can get proper output by using `\r\n` instead of just `\n` however I believe expected behavior dictates that `\n` under Windows truly outputs `\r\n` because `\n` is traditionally represents newline character(s) regardless of OS.

**Comment by benhoyt** [comment]
Good call. Fixed in https://github.com/benhoyt/goawk/commit/7c84d80620243796b2e1511e2bcb85c5fb229b36
