### ISSUE TITLE
Add support for `getline < "-"` to read from stdin

### ISSUE THREAD

**Issue by Crestwave** [benhoyt/goawk#62]
gawk, mawk and the "one true awk" have support for this, and it seems reasonable considering that POSIX requires interpretation of `-` as stdin in basically all other areas.

Only issue is that read prompts in general are a bit awkward with #47. For example:
```
$ goawk 'BEGIN { ARGV[ARGC++] = "-"; print "Enter input:"; getline; print "You entered: " $0 }'
this is my input
Enter input:
You entered: this is my input
```

**Comment by benhoyt** [comment]
Thanks for this. Merged in https://github.com/benhoyt/goawk/commit/0eb3f8c8b7889fe1feff86aed767dcdb30cbc98e.

Point about prompts noted -- I intended to fix that at some point, and even had a half-working branch, but didn't get to it. Another time...
