### ISSUE TITLE
`system("ssh user@host")` fails

### ISSUE THREAD

**Issue by xonixx** [benhoyt/goawk#65]
```
$ ./soft/goawk1.8.1 'BEGIN { system("ssh user@host") }'
Pseudo-terminal will not be allocated because stdin is not a terminal.
Welcome to Ubuntu 18.04.5 LTS (GNU/Linux 4.15.0-147-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

...
```
Command outputs the Linux greeting text and exits.

Gawk / Mawk / BWK all open interactive shell same like if you just run 

```
$ ssh user@host
```

**Comment by benhoyt** [comment]
Thanks for the report. Hmmm, I'm not sure I want to support PTYs in GoAWK. There's a fair bit of complexity to handling PTYs that I don't want to include in GoAWK, and if your AWK scripts are that interactive, I'd say there are better tools for the job. What's your use case here?

**Comment by xonixx** [comment]
Fair enough. I see your point. 

My use case: I have a tool https://github.com/xonixx/makesure which is a task/comand runner. 

Now I can us it with this file with commands definitions: https://github.com/CMLTeam/cmltemplate/blob/master/Makesurefile#L14 

So I run
```
$ ./makesure mysqld   # runs database in docker
```
then
```
$ ./makesure mysql    # interactive mysql client console opens
```

Not that I plan to use GoAWK for this tool, it works perfectly with default awks. I tested in purely out of curiosity.

**Comment by benhoyt** [comment]
Cool, thanks for the info. I think I'll close this won't-fix for now in that case.
