### ISSUE TITLE
`ENVIRON` unsupported?

### ISSUE THREAD

**Issue by xonixx** [benhoyt/goawk#73]
[`ENVIRON`](https://stackoverflow.com/a/46171338/104522) unsupported?

```
$ Indent=2 ./soft/goawk1.9.1 'BEGIN { print ENVIRON["Indent"] }'

$ Indent=2 ./soft/gawk51 'BEGIN { print ENVIRON["Indent"] }'
2
```

This is supported by mawk / bwk as well.

**Comment by benhoyt** [comment]
Thanks for the report. Yeah, I didn't support this as all the other special vars are scalars (numbers or strings), so it was a bit more work to support a special variable that was an array. But I'll look into it at some point.

**Comment by benhoyt** [comment]
Actually, I realized I already the the `ARGV` special array. This was easy to add -- done in https://github.com/benhoyt/goawk/commit/f44d0cd29c42b579871aa98a6a03062c0d01c8af
