### ISSUE TITLE
stdout and stderr are intermixed

### ISSUE THREAD

**Issue by xonixx** [benhoyt/goawk#77]
```
$ ./soft/bwk 'BEGIN { print "111"; print "222">"/dev/stderr"; print "333" }'
111
222
333

$ ./soft/mawk134 'BEGIN { print "111"; print "222">"/dev/stderr"; print "333" }'
111
222
333

$ ./soft/gawk511 'BEGIN { print "111"; print "222">"/dev/stderr"; print "333" }'
111
222
333

$ ./soft/goawk1.9.1 'BEGIN { print "111"; print "222">"/dev/stderr"; print "333" }'
222
111
333

```

This is a bit annoying since it's inconsistent with all major implementations.

This is the cause for failing test for `makesure` https://github.com/xonixx/makesure/runs/4585273788?check_suite_focus=true
And though I could write a test in a more resilient way, I would prefer to not add special logic for goawk.

I'm pretty sure this relates to https://github.com/benhoyt/goawk/issues/47.

**Comment by benhoyt** [comment]
Thanks. This is a good data point. Yeah, it's definitely related to #47. It's happening because in GoAWK stdout is buffered, stderr is not (and GoAWK doesn't currently flush stdout automatically to synchronize things, like the other AWKs do).
