### ISSUE TITLE
Incorrect parsing of complex ++ expressions

### ISSUE THREAD

**Issue by benhoyt** [benhoyt/goawk#79]
Two cases:

1) `echo 2 3 4 | goawk '{ $$0++; print $0 }'` prints `2 4 4` instead of `3`. I think this is happening because we parse this as `($($0))++` rather than `($($0++))`.
2) `BEGIN { $0="3 4 5 6 7 8 9"; a=3; print $$a++++; print }` gives a parsing error instead of printing `7\n3 4 6 6 8 8 9`.

There are two commented-out (TODO) tests in `interp/interp_test.go` for this, as well as a commented-out Gawk test (`parse1`).

**Comment by benhoyt** [comment]
I've started playing with this on the `fix-incr-decr` branch.

**Comment by vegarsti** [comment]
Can you walk through what is supposed to happen in 1? I don't understand it, sorry.

**Comment by benhoyt** [comment]
gawk, original-awk, and mawk all print `3` for that example. It's because they parse the expression as `$0++` (which returns the current value of `$0` but also post-increments `$0`); then the outer `$` does fetches `$2` but drops the result.

Whereas GoAWK parses it differently, so executes the inner `$0` first (which is `2 3 4`), then another `$`, which fetches the second field 2 (the `3`), then the `++` increments that field, creating `2 4 4`.

So it's a parsing/precedence issue. Hope that helps!

**Comment by vegarsti** [comment]
It does! Thanks!

**Comment by benhoyt** [comment]
Possibly related, but GoAWK also doesn't handle `$++a`. Compare:

```
$ echo -e '1 2 3\na b c\nd e f' | gawk '{ print $++a }'
1
b
f
$ echo -e '1 2 3\na b c\nd e f' | goawk '{ print $++a }'
<cmdline>:1:10: expected expression instead of ++
{ print $++a }
         ^
```

**Comment by vegarsti** [comment]
Was this solved by the newest release? Specifically https://github.com/benhoyt/goawk/pull/172

**Comment by benhoyt** [comment]
@vegarsti No, unfortunately not -- this is a different issue.

**Comment by vegarsti** [comment]
Okay!

**Comment by fioriandrea** [comment]
This also produces wrong results:

`./goawk 'BEGIN { $0="3 4 5 6 7 8 9"; a=3; print ($($a++)++); print $0; print a }'` prints  `7\n3 4 7 6 7 8 9\n3`, whereas
`gawk 'BEGIN { $0="3 4 5 6 7 8 9"; a=3; print ($($a++)++); print $0; print a }'` prints `7\n3 4 6 6 8 8 9\n3`
