### ISSUE TITLE
suggestion for addcomma( ) ?

### ISSUE THREAD

**Issue by mogando668** [benhoyt/goawk#97]
instead of having to use a while-loop and only process 3-digits at a time, maybe this gsub( )-based approach can speed things up ? I've just benchmarked it with a single integer slightly over 275-million digits long. it finished applying commas across  the entire input in just 6.7 seconds

```
   sub(/([0-9][0-9][0-9])+([.]|$)/, ",&")  # allocate initial mark, multiple of 3
  gsub(/[^,.][^,.][^,.]/, "&,")            # batch-process all 3-digit combos
    sub(/[,]+[.]+/, ".")                   # cleaning-up comma+period instance
  gsub(/^[^0-9]+|[^0-9]+$/, "")            # fail-safe cleanup at head and tail
```

```
      in0:  262MiB 0:00:00 [3.31GiB/s] [3.31GiB/s]  
     out9:  349MiB 0:00:06 [52.3MiB/s] [52.3MiB/s] [<=> ]
( pvE 0.1 in0 < test.txt| mawk2 ; )  6.23s user 0.45s system 99% cpu 6.715 total
```

**Comment by mogando668** [comment]
no worries. feel free to adapt it for your own use anywhere else. i just got the thing down to 4.7 seconds. not bad for formatting a single integer with 275-million-digits.

**Comment by mogando668** [comment]
side question : how do you personally feel about go versus rust

**Comment by benhoyt** [comment]
@mogando668 Heh. :-) I haven't actually used Rust. The problem it's trying to solve is important: to be a better C or C++, which seems different and more lower-level than what Go is good for -- and Go will never get there with its large runtime, goroutine scheduler, and GC. I have concerns that Rust's learning curve is too steep with its relatively complex type system and borrow checker, and just from what I've seen [Zig](https://ziglang.org/) suits my taste better. But again, I haven't tried Rust so can't speak with any kind of authority.
